// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5trH0w12-MnAxsQhR_LSe5BO5wCQoTI',
    appId: '1:640399048491:web:90a0339007b067ad824f6e',
    messagingSenderId: '640399048491',
    projectId: 'stark-282e6',
    authDomain: 'stark-282e6.firebaseapp.com',
    storageBucket: 'stark-282e6.firebasestorage.app',
    measurementId: 'G-4Q9K1W29Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0lSkx074M9QPdnAQZ7PIi9ILLINIk0E',
    appId: '1:640399048491:android:e1c04594be816cca824f6e',
    messagingSenderId: '640399048491',
    projectId: 'stark-282e6',
    storageBucket: 'stark-282e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOwR80BgjYyDkzrC4teJSNR5SgiS_uJo',
    appId: '1:640399048491:ios:f38bc22a3dd825d7824f6e',
    messagingSenderId: '640399048491',
    projectId: 'stark-282e6',
    storageBucket: 'stark-282e6.firebasestorage.app',
    iosBundleId: 'com.stark.stark',
  );
}
